[package]
name = "boolean-network-sketches"
version = "0.1.0"
authors = ["Ondřej Huvar <xhuvar@fi.muni.cz>"]
edition = "2021"
description = "Framework for Boolean network inference using BN sketches."
homepage = "https://github.com/sybila/boolean-network-sketches"
repository = "https://github.com/sybila/boolean-network-sketches"
readme = "README.md"
keywords = ["inference", "boolean-network", "model-checking", "symbolic", "systems-biology"]
categories = ["science", "simulation"]
license = "MIT"

#[profile.release]
#lto = true

[profile.test]
opt-level = 3

[[bin]]
name = "inference-with-attractors"
path = "src/bin/infer_networks_using_attractors.rs"

[[bin]]
name = "case-study-tlgl"
path = "src/bin/case_study_tlgl.rs"

[[bin]]
name = "case-study-arabidopsis"
path = "src/bin/case_study_arabidopsis.rs"

[[bin]]
name = "case-study-cns"
path = "src/bin/case_study_cns.rs"

[[bin]]
name = "small-example"
path = "src/bin/small_example.rs"

[dependencies]
biodivine-lib-bdd = ">=0.4.2, <1.0.0"
biodivine-lib-param-bn = "0.4.2"
biodivine-hctl-model-checker = { git = "https://github.com/sybila/biodivine-hctl-model-checker", branch = "dev-multiple-formulae" }
clap = { version = "3.1.6", features = ["derive"] }
termcolor = "1.1.2"
rand = "0.6.5"
