[package]
name = "network-sketches"
version = "0.1.0"
authors = ["Ondrej Huvar <ohuvar@gmail.com>"]
edition = "2021"
description = "Library for Boolean network inference using network sketches."
homepage = "https://github.com/sybila/network-sketches"
repository = "https://github.com/sybila/network-sketches"
readme = "README.md"
keywords = ["inference", "boolean-network", "model-checking", "symbolic", "systems-biology"]
categories = ["science", "simulation"]
license = "MIT"

#[profile.release]
#lto = true

[profile.test]
opt-level = 3

[[bin]]
name = "inference-with-attractors"
path = "src/bin/infer_networks_using_attractors.rs"

[[bin]]
name = "case-study-tlgl"
path = "src/bin/case_study_tlgl.rs"

[[bin]]
name = "case-study-arabidopsis"
path = "src/bin/case_study_arabidopsis.rs"

[[bin]]
name = "case-study-cns"
path = "src/bin/case_study_cns.rs"

[[bin]]
name = "sketches"
path = "src/bin/sketches.rs"

[dependencies]
biodivine-lib-bdd = "0.4.0"
biodivine-lib-param-bn = { git = "https://github.com/sybila/biodivine-lib-param-bn", branch = "hctl-experimental" }
biodivine-aeon-server = { git = "https://github.com/sybila/biodivine-aeon-server", branch = "hctl-experimental" }
biodivine-hctl-model-checker = { git = "https://github.com/sybila/biodivine-hctl-model-checker", branch = "master" }
clap = { version = "3.1.6", features = ["derive"] }
termcolor = "1.1.2"
rand = "0.6.5"
